server:
  port: 8082
  servlet:
    context-path: /transaction-service/api
spring:
  application:
  name: transaction-service
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/jb_transaction_db?useSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:jbadmin}
    password: ${DATASOURCE_PASSWORD:jbadmin}
  messages:
    basename: i18n/messages
  threads:
    virtual:
      enabled: true

account-api:
  base-url: ${ACCOUNT_API_BASE_URL:http://localhost:8081/account-service/api}