server:
  port: 8080
  servlet:
    context-path: /customer-service/api
spring:
  application:
  name: customer-service
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/jb_customer_db?useSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:jbadmin}
    password: ${DATASOURCE_PASSWORD:jbadmin}
  messages:
    basename: i18n/messages
  threads:
    virtual:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      findByAllCustomersRateLimiter:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0
      findByCustomerIdRateLimiter:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0