server:
  port: 8081
  servlet:
    context-path: /account-service/api
spring:
  application:
  name: account-service
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/jb_account_db?useSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:jbadmin}
    password: ${DATASOURCE_PASSWORD:jbadmin}
  messages:
    basename: i18n/messages
  threads:
    virtual:
      enabled: true

customer-api:
  base-url: ${CUSTOMER_API_BASE_URL:http://localhost:8080/customer-service/api}

resilience4j:
  retry:
    instances:
      findCustomerRetry:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions: org.springframework.web.client.ResourceAccessException
  ratelimiter:
    instances:
      findByCustomerIdRateLimiter:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0
      findByAccountNumberRateLimiter:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0
